[package]
name = "graaf"
version = "0.3.2"
edition = "2021"
license = "Apache-2.0"
description = "Functions and types for working with graphs"
homepage = "https://github.com/bsdrks/graaf"
documentation = "https://docs.rs/graaf"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"
keywords = ["graph", "graphs"]
categories = ["data-structures"]

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "add_edge"
harness = false

[[bench]]
name = "count_all_edges"
harness = false

[[bench]]
name = "crosscountry"
path = "benches/dijkstra_weighted_min_distances/crosscountry.rs"
harness = false

[[bench]]
name = "shortestpath1"
path = "benches/dijkstra_weighted_min_distances/shortestpath1.rs"
harness = false

[[bench]]
name = "small_graph1"
path = "benches/dijkstra_weighted_min_distances/small_graph1.rs"
harness = false