[package]
name = "graaf"
version = "0.22.0"
edition = "2021"
authors = ["Bas Dirks <bas.dirks@protonmail.com>"]
categories = ["algorithms", "data-structures", "mathematics"]
description = "Functions and types for working with graphs"
documentation = "https://docs.rs/graaf"
keywords = ["bfs", "dijkstra", "graph", "graphs"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"

[features]
default = ["adjacency_matrix"]
adjacency_matrix = ["nightly"]
nightly = []

[[bench]]
name = "add_edge"
harness = false

[[bench]]
name = "count_all_edges"
harness = false

[[bench]]
name = "cross_country"
path = "benches/distances_weighted/cross_country.rs"
harness = false

[[bench]]
name = "shortest_path_1"
path = "benches/distances_weighted/shortest_path_1.rs"
harness = false

[[bench]]
name = "small_graph_1"
path = "benches/distances_weighted/small_graph_1.rs"
harness = false

[[bench]]
name = "distances_unweighted_graph_1"
path = "benches/distances_unweighted/graph_1.rs"
harness = false