[package]
name = "graaf"
version = "0.55.2"
edition = "2021"
authors = ["Bas Dirks <bas.dirks@protonmail.com>"]
categories = ["algorithms", "data-structures", "mathematics"]
description = "Work with directed graphs."
documentation = "https://docs.rs/graaf"
keywords = ["bfs", "digraph", "dijkstra", "graph"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"
proptest = "1.4.0"

[profile.test.package.proptest]
opt-level = 3

[features]
default = ["adjacency_matrix"]
adjacency_matrix = []

[[bench]]
name = "add_arc"
path = "benches/op/add_arc.rs"
harness = false

[[bench]]
name = "size"
path = "benches/op/size.rs"
harness = false

[[bench]]
name = "single_source_distances"
path = "benches/algo/single_source_distances.rs"
harness = false

[[bench]]
name = "crosscountry"
path = "benches/algo/crosscountry.rs"
harness = false

[[bench]]
name = "shortestpath1"
path = "benches/algo/shortestpath1.rs"
harness = false
