[package]
name = "graaf"
version = "0.5.3"
edition = "2021"
license = "Apache-2.0"
description = "Functions and types for working with graphs"
homepage = "https://github.com/bsdrks/graaf"
documentation = "https://docs.rs/graaf"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"
keywords = ["graph", "graphs"]
categories = ["data-structures"]

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "add_edge"
harness = false

[[bench]]
name = "count_all_edges"
harness = false

[[bench]]
name = "crosscountry"
path = "benches/min_distances_weighted/crosscountry.rs"
harness = false

[[bench]]
name = "shortestpath1"
path = "benches/min_distances_weighted/shortestpath1.rs"
harness = false

[[bench]]
name = "small_graph_1"
path = "benches/min_distances_weighted/small_graph_1.rs"
harness = false

[[bench]]
name = "min_distances_unweighted_graph_1"
path = "benches/min_distances_unweighted/graph_1.rs"
harness = false