[package]
name = "graaf"
version = "0.64.16"
edition = "2021"
authors = ["Bas Dirks <bas.dirks@protonmail.com>"]
categories = ["algorithms", "data-structures", "mathematics"]
description = "Work with directed graphs."
documentation = "https://docs.rs/graaf"
keywords = ["bfs", "digraph", "dijkstra", "graph"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"
proptest = "1.4.0"

[profile.test.package.proptest]
opt-level = 3

[[bench]]
name = "single_source_distances"
path = "benches/algo/single_source_distances.rs"
harness = false
