[package]
name = "graaf"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "new"
harness = false

[[bench]]
name = "add_edge"
harness = false

[[bench]]
name = "count_all_edges"
harness = false

[[bench]]
name = "crosscountry"
path = "benches/dijkstra_weighted/crosscountry.rs"
harness = false

[[bench]]
name = "shortestpath1"
path = "benches/dijkstra_weighted/shortestpath1.rs"
harness = false

[[bench]]
name = "small_graph1"
path = "benches/dijkstra_weighted/small_graph1.rs"
harness = false