[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "new"
harness = false

[[bench]]
name = "add_edge"
harness = false

[[bench]]
name = "count_all_edges"
harness = false

[[bench]]
name = "kattis_shortestpath1"
harness = false