[package]
name = "graaf"
version = "0.33.0"
edition = "2021"
authors = ["Bas Dirks <bas.dirks@protonmail.com>"]
categories = ["algorithms", "data-structures", "mathematics"]
description = "Functions and types for working with graphs"
documentation = "https://docs.rs/graaf"
keywords = ["bfs", "dijkstra", "graph"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bsdrks/graaf"

[dependencies]

[lib]

[dev-dependencies]
divan = "0.1.14"
proptest = "1.4.0"

[profile.test.package.proptest]
opt-level = 3

[features]
default = ["adjacency_matrix"]
adjacency_matrix = []

[[bench]]
name = "add_edge"
path = "benches/op/add_edge.rs"
harness = false

[[bench]]
name = "count_all_edges"
path = "benches/op/count_all_edges.rs"
harness = false

[[bench]]
name = "cross_country"
path = "benches/algo/distances_weighted/cross_country.rs"
harness = false

[[bench]]
name = "shortest_path_1"
path = "benches/algo/distances_weighted/shortest_path_1.rs"
harness = false

[[bench]]
name = "small_graph_1"
path = "benches/algo/distances_weighted/small_graph_1.rs"
harness = false

[[bench]]
name = "distances_unweighted_graph_1"
path = "benches/algo/distances_unweighted/graph_1.rs"
harness = false
