format_macro_matchers = true
format_strings = true
imports_granularity = "One"
imports_layout = "Vertical"
merge_derives = true
normalize_comments = true
reorder_impl_items = true
wrap_comments = true