name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, llvm-tools-preview
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Build
        run: cargo build --verbose
      - name: Generate documentation
        run: cargo doc --verbose
      - name: Install cargo-llvm-cov
        run: cargo install
      - name: Run tests
        run: CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='coverage/cargo-test-%p-%m.profraw' cargo test
      - name: Generate coverage report
        run: grcov . --binary-path ./target/debug/ --source-dir . -t html --branch --ignore-not-existing --ignore "/*" -o ./target/debug/coverage/
      - name: Coveralls
        uses: coverallsapp/github-action@v2
