name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

  clippy:
    steps:
      - name: Run clippy
        run: cargo clippy --verbose

  fmt:
    steps:
      - name: Check formatting
        run: cargo fmt --check --verbose

  test:
    steps:
      - name: Run tests
        run: cargo test --verbose

  doc:
    steps:
      - name: Generate documentation
        run: cargo doc --verbose

  build:
    steps:
      - name: Build
        run: cargo build --verbose
