name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
      - name: Generate documentation
        run: cargo doc --verbose
